// <auto-generated />
using System;
using GovJobsWebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovJobsWebAPI.Migrations
{
    [DbContext(typeof(JobDbContext))]
    partial class JobDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GovJobsWebAPI.Models.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.JobGrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("JobGrades");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionFormattedDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .HasColumnType("longtext");

                    b.Property<string>("LabelDescription")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionFormattedDescriptions");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine")
                        .HasColumnType("longtext");

                    b.Property<string>("CityName")
                        .HasColumnType("longtext");

                    b.Property<string>("CountryCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CountrySubDivisionCode")
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<string>("LocationName")
                        .HasColumnType("longtext");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionLocations");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionOfferingType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionOfferingTypes");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionRemuneration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("MaximumRange")
                        .HasColumnType("longtext");

                    b.Property<string>("MinimumRange")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RateIntervalCode")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionRemunerations");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionSchedules");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.WhoMayApply", b =>
                {
                    b.Property<int>("WhoMayApplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WhoMayApplyId"));

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("WhoMayApplyId");

                    b.ToTable("WhoMayApplies");
                });

            modelBuilder.Entity("JobViewModel", b =>
                {
                    b.Property<string>("PositionID")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AdjudicationType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AgencyMarketingStatement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AnnouncementClosingType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ApplicationCloseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ApplyOnlineUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ApplyURI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("BenefitsDisplayDefaultText")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("BenefitsUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CommuteDistance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DetailStatusUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("DrugTestRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Evaluations")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HighGrade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HiringPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HowToApply")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("JobSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KeyRequirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LowGrade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MCOTags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MajorDuties")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationCodes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrganizationName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OtherInformation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PositionEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PositionLocationDisplay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PositionStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PositionTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PositionURI")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PromotionPotential")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PublicationStartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QualificationSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Relocation")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RemoteIndicator")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequiredDocuments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityClearance")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TeleworkEligible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TotalOpenings")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TravelCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WhatToExpectNext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WhoMayApplyId")
                        .HasColumnType("int");

                    b.Property<bool>("WithinArea")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("PositionID");

                    b.HasIndex("WhoMayApplyId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.JobCategory", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("JobCategories")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.JobGrade", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("JobGrades")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionFormattedDescription", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("PositionFormattedDescriptions")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionLocation", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("PositionLocations")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionOfferingType", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("PositionOfferingTypes")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionRemuneration", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("PositionRemunerations")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("GovJobsWebAPI.Models.PositionSchedule", b =>
                {
                    b.HasOne("JobViewModel", null)
                        .WithMany("PositionSchedules")
                        .HasForeignKey("PositionID");
                });

            modelBuilder.Entity("JobViewModel", b =>
                {
                    b.HasOne("GovJobsWebAPI.Models.WhoMayApply", "WhoMayApplies")
                        .WithMany()
                        .HasForeignKey("WhoMayApplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WhoMayApplies");
                });

            modelBuilder.Entity("JobViewModel", b =>
                {
                    b.Navigation("JobCategories");

                    b.Navigation("JobGrades");

                    b.Navigation("PositionFormattedDescriptions");

                    b.Navigation("PositionLocations");

                    b.Navigation("PositionOfferingTypes");

                    b.Navigation("PositionRemunerations");

                    b.Navigation("PositionSchedules");
                });
#pragma warning restore 612, 618
        }
    }
}
